// zodSchemas/posts.ts
import { z } from "zod";

const uuid = z.uuid();

// Exact enum values from public."PostType"
export const PostTypeSchema = z.enum(["image", "carousel", "video"]);

// Helper: enforce exactly one of three booleans is true
function exactlyOneStatusTrue(v: {
    is_active?: boolean;
    is_draft?: boolean;
    is_archived?: boolean;
}) {
    const a = v.is_active ? 1 : 0;
    const d = v.is_draft ? 1 : 0;
    const r = v.is_archived ? 1 : 0;
    return a + d + r === 1;
}

// Base shape (mirrors DB columns). Optional/nullable where DB allows NULL
export const PostBaseSchema = z
    .object({
        id: uuid.optional(), // generated by DB
        campaign_id: uuid.nullable().optional(),

        post_type: PostTypeSchema.nullable().optional(),
        title: z.string().nullable().optional(),
        content: z.string().nullable().optional(),

        // DB column is text[]; on the wire we use string[]
        hashtags: z.array(z.string()).default([]).nullable().optional(),

        is_active: z.boolean().default(false),
        is_draft: z.boolean().default(true),
        is_archived: z.boolean().default(false),

        scheduled_at: z.date().nullable().optional(),
        created_at: z.date().nullable().optional(),
        updated_at: z.date().nullable().optional(),
        deleted_at: z.date().nullable().optional(),
    })
    .superRefine((val, ctx) => {
        if (!exactlyOneStatusTrue(val)) {
            ctx.addIssue({
                code: "custom",
                message:
                    "Exactly one of is_active, is_draft, or is_archived must be true.",
                path: ["is_active"], // point to one field; UI can highlight all three
            });
        }
    });

// Create payload (client → server). Optionally include initial image links for join table.
export const PostCreateSchema = PostBaseSchema.omit({
    id: true,
    created_at: true,
    updated_at: true,
    deleted_at: true,
}).extend({
    images: z
        .array(
            z.object({
                object_id: uuid,
                position: z.number().int().min(1),
            })
        )
        .default([])
        .optional(),
});

// Update payload (partial). Still enforce status rule when any status flag is present.
export const PostUpdateSchema = z
    .object({
        id: uuid, // required to target the row
        campaign_id: uuid.nullable().optional(),
        post_type: PostTypeSchema.nullable().optional(),
        title: z.string().nullable().optional(),
        content: z.string().nullable().optional(),
        hashtags: z.array(z.string()).nullable().optional(),
        is_active: z.boolean().optional(),
        is_draft: z.boolean().optional(),
        is_archived: z.boolean().optional(),
        scheduled_at: z.date().nullable().optional(),
        deleted_at: z.date().nullable().optional(),

        // Optional full replacement of images for the post (join table)
        images: z
            .array(
                z.object({
                    object_id: uuid,
                    position: z.number().int().min(1),
                })
            )
            .optional(),
    })
    .superRefine((val, ctx) => {
        const providesStatus =
            "is_active" in val || "is_draft" in val || "is_archived" in val;
        if (providesStatus) {
            const a = val.is_active ? 1 : 0;
            const d = val.is_draft ? 1 : 0;
            const r = val.is_archived ? 1 : 0;
            if (a + d + r !== 1) {
                ctx.addIssue({
                    code: "custom",
                    message:
                        "Exactly one of is_active, is_draft, or is_archived must be true.",
                    path: ["is_active"],
                });
            }
        }
    });

// Read shape including related images (from posts_images)
export const PostWithImagesSchema = PostBaseSchema.extend({
    images: z
        .array(
            z.object({
                object_id: uuid,
                position: z.number().int().min(1),
                created_at: z.date(),
            })
        )
        .default([]),
});

export type PostType = z.infer<typeof PostTypeSchema>;
export type PostBase = z.infer<typeof PostBaseSchema>;
export type PostCreate = z.infer<typeof PostCreateSchema>;
export type PostUpdate = z.infer<typeof PostUpdateSchema>;
export type PostWithImages = z.infer<typeof PostWithImagesSchema>;
