// zodSchemas/posts.ts
import { z } from "zod";

const uuid = z.uuid();

// Exact enum values from public."PostType"
export const PostTypeSchema = z.enum(["single_image", "carousel", "video"]);

/**
 * Schema for the data required to associate an image with a post.
 * Used in create and update payloads.
 */
export const PostImageInputSchema = z.object({
    object_id: uuid,
    position: z.number().int().min(1),
});

/**
 * Schema for a post's image, including the public URL.
 * This is a read-only schema representing the final shape sent to the client.
 */
export const PostImageSchema = z.object({
    object_id: uuid,
    position: z.number().int().min(1),
    created_at: z.date(),
    /** The public URL of the image from Supabase Storage. */
    url: z.url(),
});


// Helper: enforce exactly one of three booleans is true
function exactlyOneStatusTrue(v: {
    isActive?: boolean;
    isDraft?: boolean;
    isArchived?: boolean;
}) {
    const a = v.isActive ? 1 : 0;
    const d = v.isDraft ? 1 : 0;
    const r = v.isArchived ? 1 : 0;
    return a + d + r === 1;
}

// Base shape (mirrors DB columns). Optional/nullable where DB allows NULL
export const PostBaseSchema = z
    .object({
        id: uuid.optional(), // generated by DB
        campaignId: uuid.nullable().optional(),

        postType: PostTypeSchema.nullable().optional(),
        title: z.string().nullable().optional(),
        content: z.string().nullable().optional(),

        // DB column is text[]; on the wire we use string[]
        hashtags: z.array(z.string()).default([]).nullable().optional(),

        isActive: z.boolean().default(false),
        isDraft: z.boolean().default(true),
        isArchived: z.boolean().default(false),

        scheduledAt: z.date().nullable().optional(),
        createdAt: z.date().nullable().optional(),
        updatedAt: z.date().nullable().optional(),
        deletedAt: z.date().nullable().optional(),
    })
    .superRefine((val, ctx) => {
        if (!exactlyOneStatusTrue(val)) {
            ctx.addIssue({
                code: "custom",
                message:
                    "Exactly one of is_active, is_draft, or is_archived must be true.",
                path: ["is_active"], // point to one field; UI can highlight all three
            });
        }
    });

// Create payload (client → server). Optionally include initial image links for join table.
export const PostCreateSchema = PostBaseSchema.omit({
    id: true,
    createdAt: true,
    updatedAt: true,
    deletedAt: true,
}).extend({
    images: z
        .array(PostImageInputSchema)
        .default([])
        .optional(),
});

// Update payload (partial). Still enforce status rule when any status flag is present.
export const PostUpdateSchema = z
    .object({
        id: uuid, // required to target the row
        campaignId: uuid.nullable().optional(),
        postType: PostTypeSchema.nullable().optional(),
        title: z.string().nullable().optional(),
        content: z.string().nullable().optional(),
        hashtags: z.array(z.string()).nullable().optional(),
        isActive: z.boolean().optional(),
        isDraft: z.boolean().optional(),
        isArchived: z.boolean().optional(),
        scheduledAt: z.date().nullable().optional(),
        deletedAt: z.date().nullable().optional(),

        // Optional full replacement of images for the post (join table)
        images: z
            .array(PostImageInputSchema)
            .optional(),
    })
    .superRefine((val, ctx) => {
        const providesStatus =
            "is_active" in val || "is_draft" in val || "is_archived" in val;
        if (providesStatus) {
            const a = val.isActive ? 1 : 0;
            const d = val.isDraft ? 1 : 0;
            const r = val.isArchived ? 1 : 0;
            if (a + d + r !== 1) {
                ctx.addIssue({
                    code: "custom",
                    message:
                        "Exactly one of is_active, is_draft, or is_archived must be true.",
                    path: ["is_active"],
                });
            }
        }
    });

// Read shape including related images (from posts_images)
export const PostWithImagesSchema = PostBaseSchema.extend({
    images: z
        .array(PostImageSchema)
        .default([]),
});

export type PostType = z.infer<typeof PostTypeSchema>;
export type PostImage = z.infer<typeof PostImageSchema>;
export type PostImageInput = z.infer<typeof PostImageInputSchema>;
export type PostBase = z.infer<typeof PostBaseSchema>;
export type PostCreate = z.infer<typeof PostCreateSchema>;
export type PostUpdate = z.infer<typeof PostUpdateSchema>;
export type PostWithImages = z.infer<typeof PostWithImagesSchema>;
